# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/accept_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AcceptViewer(object):
    def setupUi(self, AcceptViewer):
        AcceptViewer.setObjectName("AcceptViewer")
        AcceptViewer.resize(699, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(AcceptViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=AcceptViewer)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_btn = QtWidgets.QPushButton(parent=AcceptViewer)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        self.remove_btn = QtWidgets.QPushButton(parent=AcceptViewer)
        self.remove_btn.setCheckable(False)
        self.remove_btn.setFlat(False)
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout_2.addWidget(self.remove_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=AcceptViewer)
        self.cancel_btn.setCheckable(False)
        self.cancel_btn.setFlat(False)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(parent=AcceptViewer)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(parent=AcceptViewer)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(AcceptViewer)
        QtCore.QMetaObject.connectSlotsByName(AcceptViewer)

    def retranslateUi(self, AcceptViewer):
        _translate = QtCore.QCoreApplication.translate
        AcceptViewer.setWindowTitle(_translate("AcceptViewer", "Form"))
        self.close_btn.setText(_translate("AcceptViewer", "Закрыть"))
        self.add_btn.setText(_translate("AcceptViewer", "Добавить"))
        self.remove_btn.setText(_translate("AcceptViewer", "Удалить"))
        self.cancel_btn.setText(_translate("AcceptViewer", "Вернуть"))
        self.save_btn.setText(_translate("AcceptViewer", "Сохранить"))
