# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/accept_requests_registry.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Accept_requests_registry(object):
    def setupUi(self, Accept_requests_registry):
        Accept_requests_registry.setObjectName("Accept_requests_registry")
        Accept_requests_registry.resize(682, 567)
        self.verticalLayout = QtWidgets.QVBoxLayout(Accept_requests_registry)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh_btn = QtWidgets.QPushButton(parent=Accept_requests_registry)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=Accept_requests_registry)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.request_list = QtWidgets.QTableView(parent=Accept_requests_registry)
        self.request_list.setObjectName("request_list")
        self.horizontalLayout_2.addWidget(self.request_list)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=Accept_requests_registry)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.accept_btn = QtWidgets.QPushButton(parent=Accept_requests_registry)
        self.accept_btn.setDefault(False)
        self.accept_btn.setObjectName("accept_btn")
        self.horizontalLayout_3.addWidget(self.accept_btn)
        self.reject_btn = QtWidgets.QPushButton(parent=Accept_requests_registry)
        self.reject_btn.setObjectName("reject_btn")
        self.horizontalLayout_3.addWidget(self.reject_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Accept_requests_registry)
        QtCore.QMetaObject.connectSlotsByName(Accept_requests_registry)

    def retranslateUi(self, Accept_requests_registry):
        _translate = QtCore.QCoreApplication.translate
        Accept_requests_registry.setWindowTitle(_translate("Accept_requests_registry", "Form"))
        self.refresh_btn.setText(_translate("Accept_requests_registry", "Обновить"))
        self.close_btn.setText(_translate("Accept_requests_registry", "Закрыть"))
        self.lineEdit.setPlaceholderText(_translate("Accept_requests_registry", "Введите комментарий..."))
        self.accept_btn.setText(_translate("Accept_requests_registry", "Согласовать"))
        self.reject_btn.setText(_translate("Accept_requests_registry", "Отклонить"))
