# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/accept_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Accept_dialog(object):
    def setupUi(self, Accept_dialog):
        Accept_dialog.setObjectName("Accept_dialog")
        Accept_dialog.resize(1055, 535)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Accept_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Accept_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.type_combo_box = QtWidgets.QComboBox(parent=Accept_dialog)
        self.type_combo_box.setMinimumSize(QtCore.QSize(120, 0))
        self.type_combo_box.setObjectName("type_combo_box")
        self.type_combo_box.addItem("")
        self.type_combo_box.addItem("")
        self.horizontalLayout_2.addWidget(self.type_combo_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_table = QtWidgets.QTableView(parent=Accept_dialog)
        self.user_table.setObjectName("user_table")
        self.horizontalLayout.addWidget(self.user_table)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.add_btn = QtWidgets.QPushButton(parent=Accept_dialog)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.remove_btn = QtWidgets.QPushButton(parent=Accept_dialog)
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout.addWidget(self.remove_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.accept_table = QtWidgets.QTableView(parent=Accept_dialog)
        self.accept_table.setObjectName("accept_table")
        self.horizontalLayout.addWidget(self.accept_table)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.up_btn = QtWidgets.QPushButton(parent=Accept_dialog)
        self.up_btn.setObjectName("up_btn")
        self.verticalLayout_3.addWidget(self.up_btn)
        self.down_btn = QtWidgets.QPushButton(parent=Accept_dialog)
        self.down_btn.setObjectName("down_btn")
        self.verticalLayout_3.addWidget(self.down_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Accept_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Accept_dialog)
        self.buttonBox.accepted.connect(Accept_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Accept_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Accept_dialog)

    def retranslateUi(self, Accept_dialog):
        _translate = QtCore.QCoreApplication.translate
        Accept_dialog.setWindowTitle(_translate("Accept_dialog", "Отправить на согласование"))
        self.label.setText(_translate("Accept_dialog", "Тип согласования:"))
        self.type_combo_box.setItemText(0, _translate("Accept_dialog", "Всем сразу"))
        self.type_combo_box.setItemText(1, _translate("Accept_dialog", "По очереди"))
        self.add_btn.setText(_translate("Accept_dialog", ">"))
        self.remove_btn.setText(_translate("Accept_dialog", "<"))
        self.up_btn.setText(_translate("Accept_dialog", "/\\"))
        self.down_btn.setText(_translate("Accept_dialog", "\\/"))
