# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/contract_registry.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContractRegistry(object):
    def setupUi(self, ContractRegistry):
        ContractRegistry.setObjectName("ContractRegistry")
        ContractRegistry.resize(646, 387)
        self.verticalLayout = QtWidgets.QVBoxLayout(ContractRegistry)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_btn = QtWidgets.QPushButton(parent=ContractRegistry)
        self.refresh_btn.setAutoFillBackground(False)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_2.addWidget(self.refresh_btn)
        self.create_btn = QtWidgets.QPushButton(parent=ContractRegistry)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_2.addWidget(self.create_btn)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=ContractRegistry)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=ContractRegistry)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(ContractRegistry)
        QtCore.QMetaObject.connectSlotsByName(ContractRegistry)

    def retranslateUi(self, ContractRegistry):
        _translate = QtCore.QCoreApplication.translate
        ContractRegistry.setWindowTitle(_translate("ContractRegistry", "Form"))
        self.refresh_btn.setText(_translate("ContractRegistry", "Обновить"))
        self.create_btn.setText(_translate("ContractRegistry", "Создать"))
        self.close_btn.setText(_translate("ContractRegistry", "Закрыть"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ContractRegistry", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ContractRegistry", "Номер"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ContractRegistry", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ContractRegistry", "Контрагент"))
