# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/file_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FileDialog(object):
    def setupUi(self, FileDialog):
        FileDialog.setObjectName("FileDialog")
        FileDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(parent=FileDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.filename_lbl = QtWidgets.QLabel(parent=FileDialog)
        self.filename_lbl.setText("")
        self.filename_lbl.setObjectName("filename_lbl")
        self.horizontalLayout.addWidget(self.filename_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.attach_file = QtWidgets.QPushButton(parent=FileDialog)
        self.attach_file.setObjectName("attach_file")
        self.verticalLayout.addWidget(self.attach_file)
        self.delete_file = QtWidgets.QPushButton(parent=FileDialog)
        self.delete_file.setObjectName("delete_file")
        self.verticalLayout.addWidget(self.delete_file)
        self.open_file = QtWidgets.QPushButton(parent=FileDialog)
        self.open_file.setObjectName("open_file")
        self.verticalLayout.addWidget(self.open_file)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=FileDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FileDialog)
        QtCore.QMetaObject.connectSlotsByName(FileDialog)

    def retranslateUi(self, FileDialog):
        _translate = QtCore.QCoreApplication.translate
        FileDialog.setWindowTitle(_translate("FileDialog", "Dialog"))
        self.label_4.setText(_translate("FileDialog", "Файл:"))
        self.attach_file.setText(_translate("FileDialog", "Прикрепить файл"))
        self.delete_file.setText(_translate("FileDialog", "Удалить файл"))
        self.open_file.setText(_translate("FileDialog", "Открыть файл"))
