# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/nomenclature_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Nomenclature_dialog(object):
    def setupUi(self, Nomenclature_dialog):
        Nomenclature_dialog.setObjectName("Nomenclature_dialog")
        Nomenclature_dialog.resize(522, 379)
        self.verticalLayout = QtWidgets.QVBoxLayout(Nomenclature_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=Nomenclature_dialog)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=Nomenclature_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Nomenclature_dialog)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(parent=Nomenclature_dialog)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Nomenclature_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Nomenclature_dialog)
        self.buttonBox.accepted.connect(Nomenclature_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Nomenclature_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Nomenclature_dialog)

    def retranslateUi(self, Nomenclature_dialog):
        _translate = QtCore.QCoreApplication.translate
        Nomenclature_dialog.setWindowTitle(_translate("Nomenclature_dialog", "Выбор номенклатуры"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Nomenclature_dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Nomenclature_dialog", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Nomenclature_dialog", "Единица измерения"))
        self.lineEdit.setPlaceholderText(_translate("Nomenclature_dialog", "Наименование"))
        self.lineEdit_2.setPlaceholderText(_translate("Nomenclature_dialog", "Ед. измерения"))
        self.pushButton.setText(_translate("Nomenclature_dialog", "Сохранить"))
