# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/request_accept_widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Request_accept(object):
    def setupUi(self, Request_accept):
        Request_accept.setObjectName("Request_accept")
        Request_accept.resize(626, 389)
        self.verticalLayout = QtWidgets.QVBoxLayout(Request_accept)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=Request_accept)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=Request_accept)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=Request_accept)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=Request_accept)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Request_accept)
        QtCore.QMetaObject.connectSlotsByName(Request_accept)

    def retranslateUi(self, Request_accept):
        _translate = QtCore.QCoreApplication.translate
        Request_accept.setWindowTitle(_translate("Request_accept", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Request_accept", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Request_accept", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Request_accept", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Request_accept", "Отчество"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Request_accept", "Статус"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Request_accept", "Дата"))
        self.label.setText(_translate("Request_accept", "Комментарий:"))
        self.pushButton.setText(_translate("Request_accept", "Удалить согласованта"))
