# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/request_registry.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Request_registry(object):
    def setupUi(self, Request_registry):
        Request_registry.setObjectName("Request_registry")
        Request_registry.resize(663, 457)
        self.verticalLayout = QtWidgets.QVBoxLayout(Request_registry)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh_btn = QtWidgets.QPushButton(parent=Request_registry)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.create_btn = QtWidgets.QPushButton(parent=Request_registry)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout.addWidget(self.create_btn)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=Request_registry)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=Request_registry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.category_combobox = QtWidgets.QComboBox(parent=Request_registry)
        self.category_combobox.setObjectName("category_combobox")
        self.horizontalLayout_2.addWidget(self.category_combobox)
        self.label_2 = QtWidgets.QLabel(parent=Request_registry)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=Request_registry)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.request_list = QtWidgets.QTableView(parent=Request_registry)
        self.request_list.setObjectName("request_list")
        self.verticalLayout.addWidget(self.request_list)

        self.retranslateUi(Request_registry)
        QtCore.QMetaObject.connectSlotsByName(Request_registry)

    def retranslateUi(self, Request_registry):
        _translate = QtCore.QCoreApplication.translate
        Request_registry.setWindowTitle(_translate("Request_registry", "Form"))
        self.refresh_btn.setText(_translate("Request_registry", "Обновить"))
        self.create_btn.setText(_translate("Request_registry", "Создать"))
        self.close_btn.setText(_translate("Request_registry", "Закрыть"))
        self.label.setText(_translate("Request_registry", "Категория:"))
        self.label_2.setText(_translate("Request_registry", "Статус:"))
        self.comboBox.setItemText(0, _translate("Request_registry", "-"))
        self.comboBox.setItemText(1, _translate("Request_registry", "Не согласовано"))
        self.comboBox.setItemText(2, _translate("Request_registry", "Согласовано"))
        self.comboBox.setItemText(3, _translate("Request_registry", "Отклонено"))
        self.comboBox.setItemText(4, _translate("Request_registry", "Выполнено"))
