# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/request_category_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Request_category(object):
    def setupUi(self, Request_category):
        Request_category.setObjectName("Request_category")
        Request_category.resize(512, 347)
        self.verticalLayout = QtWidgets.QVBoxLayout(Request_category)
        self.verticalLayout.setObjectName("verticalLayout")
        self.category_list = QtWidgets.QListWidget(parent=Request_category)
        self.category_list.setObjectName("category_list")
        self.verticalLayout.addWidget(self.category_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_edit = QtWidgets.QLineEdit(parent=Request_category)
        self.name_edit.setText("")
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout.addWidget(self.name_edit)
        self.add_btn = QtWidgets.QPushButton(parent=Request_category)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Request_category)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Request_category)
        self.buttonBox.accepted.connect(Request_category.accept) # type: ignore
        self.buttonBox.rejected.connect(Request_category.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Request_category)

    def retranslateUi(self, Request_category):
        _translate = QtCore.QCoreApplication.translate
        Request_category.setWindowTitle(_translate("Request_category", "Dialog"))
        self.category_list.setSortingEnabled(True)
        self.name_edit.setPlaceholderText(_translate("Request_category", "Введите наименование..."))
        self.add_btn.setText(_translate("Request_category", "Добавить"))
