# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/vender_registry.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VenderRegistry(object):
    def setupUi(self, VenderRegistry):
        VenderRegistry.setObjectName("VenderRegistry")
        VenderRegistry.resize(560, 421)
        self.verticalLayout = QtWidgets.QVBoxLayout(VenderRegistry)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh_btn = QtWidgets.QPushButton(parent=VenderRegistry)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.create_btn = QtWidgets.QPushButton(parent=VenderRegistry)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout.addWidget(self.create_btn)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=VenderRegistry)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=VenderRegistry)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(VenderRegistry)
        QtCore.QMetaObject.connectSlotsByName(VenderRegistry)

    def retranslateUi(self, VenderRegistry):
        _translate = QtCore.QCoreApplication.translate
        VenderRegistry.setWindowTitle(_translate("VenderRegistry", "Form"))
        self.refresh_btn.setText(_translate("VenderRegistry", "Обновить"))
        self.create_btn.setText(_translate("VenderRegistry", "Создать"))
        self.close_btn.setText(_translate("VenderRegistry", "Закрыть"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VenderRegistry", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VenderRegistry", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("VenderRegistry", "Адрес"))
