# Form implementation generated from reading ui file '/Users/arsenijkarpov/Documents/Колледж/3 курс/Курсовые/project/interfaces/vender_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Vender_dialog(object):
    def setupUi(self, Vender_dialog):
        Vender_dialog.setObjectName("Vender_dialog")
        Vender_dialog.resize(558, 425)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Vender_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=Vender_dialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_edit = QtWidgets.QLineEdit(parent=Vender_dialog)
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout.addWidget(self.name_edit)
        self.address_edit = QtWidgets.QLineEdit(parent=Vender_dialog)
        self.address_edit.setObjectName("address_edit")
        self.horizontalLayout.addWidget(self.address_edit)
        self.add_btn = QtWidgets.QPushButton(parent=Vender_dialog)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Vender_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Vender_dialog)
        self.buttonBox.accepted.connect(Vender_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Vender_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Vender_dialog)

    def retranslateUi(self, Vender_dialog):
        _translate = QtCore.QCoreApplication.translate
        Vender_dialog.setWindowTitle(_translate("Vender_dialog", "Dialog"))
        self.name_edit.setPlaceholderText(_translate("Vender_dialog", "Введите наименование.."))
        self.address_edit.setPlaceholderText(_translate("Vender_dialog", "Введите адрес..."))
        self.add_btn.setText(_translate("Vender_dialog", "Добавить"))
